"""refactoring

Revision ID: a2e737935f8c
Revises: f0c1a429e432
Create Date: 2018-06-10 00:57:52.752852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2e737935f8c'
down_revision = 'f0c1a429e432'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('library_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location')
    )
    op.create_table('resoures_metadata',
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('meta_data_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meta_data_id'], ['metadata.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('resource_id', 'meta_data_id')
    )
    op.drop_table('users')
    op.drop_table('groups')
    op.drop_table('links')
    op.drop_table('users_groups')
    op.add_column('libraries', sa.Column('description', sa.String(), nullable=True))
    op.add_column('libraries', sa.Column('hash', sa.String(), nullable=True))
    op.add_column('libraries', sa.Column('name', sa.String(), nullable=True))
    op.add_column('libraries', sa.Column('secret', sa.String(), nullable=True))
    op.drop_constraint(None, 'libraries', type_='foreignkey')
    op.drop_column('libraries', 'owner_id')
    op.drop_constraint(None, 'metadata', type_='foreignkey')
    op.drop_column('metadata', 'link_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metadata', sa.Column('link_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'metadata', 'links', ['link_id'], ['id'])
    op.add_column('libraries', sa.Column('owner_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'libraries', 'groups', ['owner_id'], ['id'])
    op.drop_column('libraries', 'secret')
    op.drop_column('libraries', 'name')
    op.drop_column('libraries', 'hash')
    op.drop_column('libraries', 'description')
    op.create_table('users_groups',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('keyword_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'keyword_id')
    )
    op.create_table('links',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('url', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('groups',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('token', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('pwhash', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('resoures_metadata')
    op.drop_table('resources')
    # ### end Alembic commands ###
